# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Bash@3
  inputs:
    script: 
      # Get the commit ID of the previous build
      previousCommit=$(Build.SourceVersion)

      # Get the commit ID of the current build
      currentCommit=$(Build.SourceVersion)

      # Get the list of changed files between the two commits
      changedFiles=$(git diff --name-only $previousCommit $currentCommit)

      # Save the list of changed files to a variable
      echo "##vso[task.setvariable variable=ChangedFiles]$changedFiles"